### ISSUE TITLE
Telegram web issue

### ISSUE THREAD

**Issue by chrfwow** [j-delaney/back-to-backspace#10]
If backspace is pressed in the Telegram Web chat, it will go back to the previous page

**Comment by j-delaney** [comment]
Resolved by #12

**Comment by j-delaney** [comment]
@chrfwow: Thanks to a fix by @maximbaz, it should be fixed now. I've uploaded the newest version to Chrome's WebStore and it should be available within an hour. I'm really sorry I let that bug slip through. I'll be increasing the tests I run before each version in the future.
