### ISSUE TITLE
YouTube Comments

### ISSUE THREAD

**Issue by UtopiaOpera** [j-delaney/back-to-backspace#11]
I've only just noticed this so not sure if it's because of an update via yourself or YouTube, or maybe even localised to me, but using backspace whilst focused in the comment form input sends you back a page rather than deleting text. Pressing backspace in text input here on GitHub works as normal.

Win10 64bit / Chrome Version 52.0.2743.82 m

**Comment by j-delaney** [comment]
Resolved by #12

**Comment by j-delaney** [comment]
@UtopiaOpera: Thanks to a fix by @maximbaz, it should be resolved now. I've uploaded the newest version to Chrome's WebStore and it should be available within an hour. I'm really sorry I let that bug slip through. I'll be increasing the tests I run before each version in the future.
