### ISSUE TITLE
Microsoft Outlook Live

### ISSUE THREAD

**Issue by Kibetha** [j-delaney/back-to-backspace#13]
(Or whatever Hotmail is called nowadays.) When writing an email, the email textbox doesn't seem to register and pressing backspace takes you back a page rather than deleting text.

**Comment by j-delaney** [comment]
@Kibetha: Thanks to a fix by @maximbaz, it should be fixed now. I've uploaded the newest version to Chrome's WebStore and it should be available within an hour. I'm really sorry I let that bug slip through. I'll be increasing the tests I run before each version in the future.

**Comment by Kibetha** [comment]
Thank you very much for all your hard work!
