### ISSUE TITLE
Add shift backspace

### ISSUE THREAD

**Issue by davidgomes** [j-delaney/back-to-backspace#16]
Hi, Chrome also used to have the Shift-Backspace functionality. Would you be able to implement this as well?

It just goes forward instead of backward.

**Comment by t-p-l-k** [comment]
@davidgomes isn't it already implemented?
```// Go forward in history if the shift key is being held down.
                // Go backwards in history if the shift key is not being held down.
                history.go( event.shiftKey ? 1 : -1 );```
Works for me.

**Comment by davidgomes** [comment]
Actually it works for me too.
