### ISSUE TITLE
Backspace when erasing text on Facebook.com will navigate back

### ISSUE THREAD

**Issue by hanxue** [j-delaney/back-to-backspace#2]
In any text input fields on Facebook's website, typing backspace will navigate back to the last URL

**Comment by j-delaney** [comment]
Thanks for the bug report! What version of Chrome and what OS are you using?

**Comment by j-delaney** [comment]
The newest version should have fixed this! Once your installed copy of the extension has updated to 1.1.0 (you can check this at [chrome://extensions/](chrome://extensions/)) please let me know if the bug is still there.

**Comment by hanxue** [comment]
Yes, bug is fixed and backspace is working as expected on Facebook.com

Thanks for the update!
