### ISSUE TITLE
Back navigates to empty "new tab"

### ISSUE THREAD

**Issue by adenisyuk** [j-delaney/back-to-backspace#6]
1. Open new tab (ctrl+t)
2. Type any website address, hit enter

AR: Observe Back button on the browser's top left corner - it's enabled (and navigates to to that empty "new tab" as well as Backspase click).
ER: Empty "new tab" should not be considered as an item of page back stack

**Comment by jaerie** [comment]
Experiencing this bug as well

**Comment by OlsonDev** [comment]
Chrome has behaved this way as long as I remember; I don't think it's this extension's job to fix that. Report a bug to the Chrome team instead.

**Comment by t-p-l-k** [comment]
Yeah, don't really think it's a bug too.

**Comment by hiddenpk1** [comment]
This isn't a bug. The new tab page is an actual page. People use it as a quasi home page now with their own favorites and google search. Chrome has always behaved this way.
