### ISSUE TITLE
Facebook chat incompatability

### ISSUE THREAD

**Issue by thrown-awa** [j-delaney/back-to-backspace#9]
Whenever Facebook Messenger's chat box is active, if backspace is pressed it will attempt to go back a page despite a text box being active.

**Comment by j-delaney** [comment]
Resolved by #12

**Comment by j-delaney** [comment]
@thrown-awa: Thanks to a fix by @maximbaz, it should be fixed now. I've uploaded the newest version to Chrome's WebStore and it should be available within an hour. I'm really sorry I let that bug slip through. I'll be increasing the tests I run before each version in the future.
